spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager?serverTimezone=UTC
    username: root
    password: 1677613325
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

